name: Big Bold CMO
favicon: null
layout_spectrum: 0.53316
typography_spectrum: 0.82466
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#318496'
    - '#57adbc'
    - '#a7f5ff'
    - '#2c6137'
  brandStrength: 0.5
  lightness: 0.3329590561334044
  saturation: 0.5
  rhythmicContrast: 0.40826166537590325
purpose: []
