name: Big Bold CMO
favicon: null
layout_spectrum: 0.53316
typography_spectrum: 0.82466
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#5e7888'
    - '#23343d'
    - '#e2f0f5'
    - '#8fcae0'
  brandStrength: 0.846008937805891
  lightness: 0.3329590561334044
  saturation: 0.1723492406308651
  rhythmicContrast: 0.40826166537590325
purpose: []
